name: fluffy

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.0 <0.41.0'
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #  https://pub.flutter-io.cn/packages/provider
  #  主工程也要添加依赖
  provider: ^4.3.2+2

  dio: ^3.0.10

  cupertino_icons: ^0.1.3

  fluro: ^1.6.3

  #  cached_network_image: ^2.3.2+1

  #https://www.jianshu.com/p/3b9992b84e60
  source_gen: ^0.9.0
  mustache4dart2: ^0.1.0

#dev_dependencies:
#  build_runner: ^1.0.0