name: fluffy

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #  https://pub.flutter-io.cn/packages/provider
  #  主工程也要添加依赖
  provider: ^4.3.2+2

  cupertino_icons: ^0.1.3

  fluro: ^1.6.3